// -------------------------------------------------------------
// 
// File Name: hdl_prj/hdlsrc/test1/test1.v
// Created: 2016-05-02 18:06:20
// 
// Generated by MATLAB 8.5 and HDL Coder 3.6
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0
// Target subsystem base rate: 0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: test1
// Source Path: test1
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module test1
          (
           In1,
           Out1
          );


  input   In1;
  output  Out1;




  assign Out1 = In1;

endmodule  // test1

